name: Build Go CLI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:

  build:
    name: Release Go binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            ext: ''
          - goos: darwin
            goarch: arm64
            ext: ''
          - goos: windows
            goarch: amd64
            ext: '.exe'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'
        cache: false

    - name: Build
      run: |
        mkdir -p dist
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o dist/go-christmas-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} ./

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-christmas-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
        path: dist/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
